services:
  - type: web
    name: stock-alert-app
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --ws-ping-interval 20 --ws-ping-timeout 20
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: RENDER_EXTERNAL_URL
        value: "https://stock-alert-app-xa08.onrender.com"
    plan: free
